### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by preronagit** [AnuverseHQ/qRPC-Socket#3]

**Comment by preronagit** [comment]
@anugrahzeputra I want to resolve this issue. Can you please assign it to me under the label of Hacktoberfest?

**Comment by anugrahzeputra** [comment]
@preronagit thanks for raising this as an issue. could you make it and describe me what is it ? i need to learn it properly.

**Comment by preronagit** [comment]
@anugrahzeputra Contributing.md file will act as a pathway for the contributors and will guide them regarding how to contribute in a project ( eg. how to fork, how to make a pull request etc).

**Comment by preronagit** [comment]
@anugrahzeputra You have to add the label hacktoberfest to your repository otherwise it's showing that your repo is not participating in hacktoberfest.

**Comment by anugrahzeputra** [comment]
@preronagit thank you for the reminders. i have put hactoberfest label on this repo. thanks for participating

**Comment by kartik-212004** [comment]
I would like to resolve this issue. Please assign it to me.
Thanks

**Comment by anugrahzeputra** [comment]
@kartik-212004 noted. i appreciate it. thanks

**Comment by anugrahzeputra** [comment]
i already accept the pull request that you add. thank you for participating @kartik-212004 @preronagit

**Comment by kartik-212004** [comment]
@anugrahzeputra can u merge my pr please...its kindof necessary for the hacktober fest

**Comment by anugrahzeputra** [comment]
okay, i have merge it before. please enlighten me, what can i do for you.

**Comment by kartik-212004** [comment]
Thanks a lot
